<?php

declare(strict_types=1);

namespace Pushery\SQLens\Drivers\Pgsql\Rules\L6;

use Pushery\SQLens\Categories\Category;
use Pushery\SQLens\Contracts\DeclaresJudgedObjectTypes;
use Pushery\SQLens\Findings\UndeterminedReason;
use Pushery\SQLens\Levels\Level;
use Pushery\SQLens\Rules\AbstractCatalogRule;
use Pushery\SQLens\Rules\Keys\SerialColumn;
use Pushery\SQLens\Rules\RuleIdFormat;
use Pushery\SQLens\Rules\RuleVerdict;
use Pushery\SQLens\Rules\Suite;
use Pushery\SQLens\Subjects\SchemaObject;
use Pushery\SQLens\Subjects\SchemaObjectType;

/**
 * A key generated by `serial` rather than by an identity column.
 *
 * ## What `serial` actually leaves behind
 *
 * `id bigserial` is not a type. It is a macro that expands into four separate things: a `bigint`
 * column, a sequence, a column default of `nextval('…')`, and a dependency tying the sequence's
 * lifetime to the column's. After the statement runs, the catalog reports the column as `bigint`,
 * identical to what `bigint GENERATED BY DEFAULT AS IDENTITY` produces — and the four pieces sit
 * there as four independently editable objects.
 *
 * That separateness is the whole issue, and it shows up in ordinary work rather than in theory:
 *
 * - **The default is detachable.** `ALTER TABLE … ALTER COLUMN id DROP DEFAULT` leaves a column
 *   that looks like a key and silently stops generating values. Nothing in the schema records that
 *   this used to be a `serial`. An identity column's generation is part of the column: dropping it
 *   takes a statement that says so, `DROP IDENTITY`.
 * - **The sequence carries its own permissions.** A role granted `INSERT` on the table still gets
 *   `permission denied for sequence` unless it was separately granted `USAGE` on the sequence. This
 *   is the single most common serial surprise, it appears only at runtime under the role that was
 *   not the owner, and an identity column has no such second grant because its sequence is internal.
 * - **The value is not protected.** `serial` is `GENERATED BY DEFAULT` at best: an explicit insert
 *   of `id` is accepted, the sequence is not advanced, and the collision arrives later as a
 *   duplicate-key error on a row nobody was writing at the time. `GENERATED ALWAYS AS IDENTITY`
 *   refuses the explicit value outright, which is the behavior most people believed they had.
 *
 * Identity columns are also the SQL standard's spelling, which matters for anything that reads a
 * schema and expects to find one.
 *
 * ## Why this is level 6 and not a defect
 *
 * `serial` works. It has worked for two decades, Laravel's own `bigIncrements()` still produces it,
 * and a schema full of it is not broken — which is exactly what level 6 is for. The finding is an
 * invitation to decide, not a verdict, and the report says so.
 *
 * ## The three neighbors this refuses to confuse with a `serial`
 *
 * Detection reads {@see SerialColumn}, which joins three catalog facts rather than looking at a
 * type name — there is no type to look at. The reason it is that careful is that three ordinary,
 * deliberate schema shapes sit right next to `serial` and each one would be a false positive:
 * an identity column, a hand-managed sequence several columns default from, and a sequence owned
 * by a column purely so it is dropped along with it.
 */
final class SerialNotIdentityRule extends AbstractCatalogRule implements DeclaresJudgedObjectTypes
{
    /**
     * Tables only — a run that read none produced no subject for this rule, and the report has to be
     * able to say so rather than let the silence read as a clean answer.
     *
     * @return non-empty-list<SchemaObjectType>
     */
    public function judgedObjectTypes(): array
    {
        return [SchemaObjectType::Table];
    }

    /**
     * The ticket proposed `PG.L6.TYPE.SERIAL_NOT_IDENTITY`; the shipped format allows three
     * segments ({@see RuleIdFormat::PATTERN}), so the `TYPE` grouping is
     * dropped rather than the format widened. Rule ids are public API from 1.0, and a fourth
     * segment introduced for one rule would be a second id shape every consumer has to parse.
     */
    public function id(): string
    {
        return 'PG.L6.SERIAL_NOT_IDENTITY';
    }

    public function level(): Level
    {
        return Level::TypeIdiom;
    }

    public function category(): Category
    {
        return Category::Idiom;
    }

    /** @return list<Suite> */
    public function suites(): array
    {
        return [Suite::Audit];
    }

    /** @return list<RuleVerdict> */
    public function judgeSchemaObject(SchemaObject $object): array
    {
        if ($object->type !== SchemaObjectType::Table) {
            return [];
        }

        $serial = SerialColumn::on($object);

        if ($serial !== []) {
            return [RuleVerdict::flag($this->message($object, $serial))];
        }

        $unreadable = SerialColumn::unreadable($object);

        if ($unreadable === []) {
            return [];
        }

        return [RuleVerdict::undetermined(sprintf(
            'On %s, %s draws from a sequence it owns, but through a default this cannot read as the `serial` macro '
            .'(`serial` produces exactly `nextval(...)` and nothing around it). Whether the column should become an '
            .'identity column is therefore unanswered: an identity column cannot express a wrapped default, so '
            .'recommending the conversion would change what the column defaults to, and reporting nothing would '
            .'claim a check that did not happen.',
            $object->qualifiedName,
            implode(', ', $unreadable),
        ), UndeterminedReason::SequenceOwnershipUnclear)];
    }

    /**
     * ONE message for the table and every `serial` column on it.
     *
     * A catalog finding is located at the object and results are deduplicated by rule id and
     * location, so a verdict per column would arrive as one with the rest dropped without a word.
     *
     * @param  array<string, string>  $serial
     */
    private function message(SchemaObject $object, array $serial): string
    {
        $columns = array_map(
            static fn (string $column, string $sequence): string => sprintf('%s (sequence %s)', $column, $sequence),
            array_keys($serial),
            array_values($serial),
        );

        return sprintf(
            'On %s, %s %s generated by `serial` rather than by an identity column. `serial` is a macro, not a type: '
            .'the column, its sequence and its default are three separate objects, so the default can be dropped '
            .'without a trace, the sequence needs its own USAGE grant before another role can insert, and an explicit '
            .'value is accepted silently and collides later. `GENERATED ALWAYS AS IDENTITY` keeps all of that inside '
            .'the column. Not a defect — `bigIncrements()` still produces `serial` — but a decision worth making on '
            .'purpose.',
            $object->qualifiedName,
            implode(', ', $columns),
            count($columns) === 1 ? 'is' : 'are',
        );
    }
}
