<?php

declare(strict_types=1);

namespace Pushery\SQLens\Rules\Lifecycle;

use Override;
use Pushery\SQLens\Contracts\ProvidesRemediation;
use Pushery\SQLens\Findings\Confidence;
use Pushery\SQLens\Findings\DowntimeClass;
use Pushery\SQLens\Findings\RemediationPayload;
use Pushery\SQLens\Levels\Level;
use Pushery\SQLens\Remediation\NoSafeSequenceTemplate;
use Pushery\SQLens\Rules\RuleDriverNotes;
use Pushery\SQLens\Subjects\DownMethodState;
use Pushery\SQLens\Subjects\MigrationStatementView;

/**
 * A migration that cannot be rolled back: its `down()` is missing, or it runs nothing.
 *
 * The moment this matters is the moment a deploy is already going wrong — which is the worst
 * possible time to find out. It is also the thing no `.sql` linter can see: rollback is a
 * FRAMEWORK concept, expressed in PHP, and a tool that only reads SQL has nothing to look at.
 * That makes it one of the few checks that is SQLens's alone.
 *
 * ## Why the verdict is static, and why that is not a compromise
 *
 * A run cannot answer this. A missing `down()` emits no statements, and neither does an empty
 * one, so at runtime both are indistinguishable from a `down()` that legitimately had nothing to
 * undo. Only the file holds the difference — {@see DownMethodState} reads it off the parse the
 * pre-scan already did, so the check also survives in the sub-second single-file fast path where
 * a shadow database could never run. That is exactly where a pre-commit hook lives.
 *
 * The neighboring runtime questions belong to the roundtrip and stay there: whether `down()`
 * RAISED (`CAP.L0.DOWN_FAILED`) and whether it actually undid the schema
 * (`CAP.L0.DOWN_NOT_INVERTIBLE`). This rule asks something they cannot: whether there is a
 * rollback path at all, without running anything.
 *
 * ## What it deliberately does not do
 *
 * It reports once per migration, on the first statement, rather than on every one — the fact is
 * about the migration, and repeating it per statement would bury a real per-statement finding
 * under it.
 *
 * It stays silent when nothing looked. A run whose pre-scan never saw the file carries no state,
 * and a rule that read that absence as "missing" would invent a finding out of its own blind
 * spot. `null` is not `Missing` (see {@see DownMethodState}).
 *
 * It also stays silent on a migration that emitted no statements at all: there is nothing there
 * to be irreversible, and the capture layer already reports an empty capture on its own axis.
 */
final class DownMissingRule extends AbstractLifecycleRule implements ProvidesRemediation
{
    /** The considered `none` — the inverse of THIS up() is the project's to write. */
    private readonly NoSafeSequenceTemplate $template;

    public function __construct(string $projectRoot, ?RuleDriverNotes $driverNotes = null)
    {
        parent::__construct($projectRoot, $driverNotes);

        $this->template = new NoSafeSequenceTemplate;
    }

    public function id(): string
    {
        return 'GEN.L4.DOWN_MISSING';
    }

    /**
     * A considered `none`: the rollback that belongs here is the inverse of THIS `up()`, and only
     * the project knows what that is.
     *
     * The temptation is real and worth naming, because a template here would look so plausible: the
     * statement stream is right there, and inverting `ADD COLUMN` into `DROP COLUMN` is mechanical.
     * It is also how a generated `down()` DESTROYS DATA — the inverse of "add a column and backfill
     * it" is not "drop the column", it is "drop the column and lose everything written into it
     * since". A rollback is run when a deploy is already going wrong, which is the worst possible
     * moment to discover that the way back was generated by a linter that could not see the data.
     *
     * What the reason does instead is name the answer this rule actually wants, and it is not always
     * a `down()` that undoes something: where the change genuinely cannot be undone, a `down()` that
     * THROWS with that reason is a complete and correct answer. That distinction is the whole value
     * here — it turns "you are missing something" into "here are the two things either of which
     * finishes this", one of which is often five lines.
     */
    public function remediationFor(MigrationStatementView $statement): ?RemediationPayload
    {
        // The same reading the verdict makes: no flag, no material. Calling it for its NULL-ness
        // rather than duplicating its three conditions is what keeps the two from disagreeing about
        // which migration they are describing.
        if ($this->judge($statement) === null) {
            return null;
        }

        return $this->template->payload(
            'sqlens::messages.remediation.no_safe_sequence.down_missing',
            'sqlens::messages.remediation.no_safe_sequence.down_verification',
            $this->id(),
            $this->downtimeClass(),
        );
    }

    /**
     * Level 4 — the deploy-window band, the same one `PG.L4.DROP_WITHOUT_DEPLOY_WINDOW` sits in.
     *
     * Nothing here is destroyed and nothing is locked; what is missing is the way BACK out of a
     * deploy. That is the question level 4 asks, and placing it lower would put a rollback-path
     * concern in the destructive band where it would fire long before a project has opted into
     * reasoning about deploy windows at all.
     */
    public function level(): Level
    {
        return Level::BackwardCompatibility;
    }

    /**
     * Online: the missing rollback path costs no downtime when the migration runs. It costs it
     * later, when someone needs the rollback and there is none — which is the level's business,
     * not the downtime axis's.
     */
    public function downtimeClass(): DowntimeClass
    {
        return DowntimeClass::Online;
    }

    /**
     * Deterministic: whether a method is declared, and whether its body runs anything, are facts
     * about the file. There is no estimate in this verdict.
     */
    #[Override]
    public function confidence(): Confidence
    {
        return Confidence::Deterministic;
    }

    protected function judge(MigrationStatementView $statement): ?string
    {
        // Once per migration, on the first statement — the fact is about the migration.
        if (! $this->isFirstStatement($statement)) {
            return null;
        }

        $state = $statement->migration->downMethodState;

        if (! $state instanceof DownMethodState || $state->isReversible()) {
            return null;
        }

        return match ($state === DownMethodState::Missing) {
            true => 'This migration declares no down(), so it cannot be rolled back. The moment that '
              .'matters is the moment a deploy is already going wrong, and discovering it there is '
              .'the worst case. Write the down() that undoes this migration\'s up() — and if the '
              .'change genuinely cannot be undone (a dropped column\'s data is gone), say so in a '
              .'down() that throws with that reason, so the answer is recorded rather than absent.',
            false => 'This migration\'s down() runs nothing — an empty body, or only a comment — so it '
              .'reports success while undoing nothing, which is worse than having none: a rollback '
              .'appears to work and leaves the schema where it was. Either implement it, or throw '
              .'with the reason the change cannot be undone.',
        };
    }
}
