<?php

declare(strict_types=1);

namespace Pushery\SQLens\Rules\Keys;

use Pushery\SQLens\Rules\Coverage\ForeignKeyIndexCoverage;
use Pushery\SQLens\Subjects\SchemaObject;

/**
 * Which of a table's columns are `serial`, told apart from every neighboring shape.
 *
 * ## `serial` is not a type, so no type check can find it
 *
 * `id bigserial` produces a `bigint` column, a sequence, a default of `nextval('…')`, and an AUTO
 * dependency in `pg_depend` tying the sequence's lifetime to the column's. `format_type` reports
 * `bigint` afterwards, exactly as it does for `bigint GENERATED BY DEFAULT AS IDENTITY`. The macro
 * leaves its signature in the dependency graph and nowhere else, which is why this reads three
 * catalog facts instead of a type name.
 *
 * ## The four shapes, and why three of them are not `serial`
 *
 * All measured on PostgreSQL 18.4 rather than reasoned about:
 *
 * | shape | `attidentity` | default | `pg_depend` |
 * |---|---|---|---|
 * | `bigserial` | empty | `nextval('t_id_seq')` | `a` on THIS column |
 * | `GENERATED … AS IDENTITY` | `a` / `d` | none at all | `i` on this column |
 * | a shared or hand-managed sequence | empty | `nextval('s')` | nothing on this column |
 * | a sequence owned for cleanup only | empty | none | `a` on this column |
 *
 * An identity column has no `pg_attrdef` row whatsoever — its sequence is internal — so the three
 * facts separate cleanly and none of the three neighbors can be mistaken for the macro.
 *
 * The third row is the one worth stating twice: a sequence somebody created by hand and defaults
 * several columns from is a deliberate design, not a `serial` that got away. It is not reported,
 * and the reason it is not reported is that the AUTO dependency sits on the OWNING column — which
 * may be a sibling on the same table. A check that asked "does this table own a sequence" would
 * call the borrowing column serial; this asks about the column.
 */
final readonly class SerialColumn
{
    /**
     * The columns that are `serial`: no identity, the exact macro default, and their own sequence.
     *
     * @return array<string, string> column name => the sequence it owns
     */
    public static function on(SchemaObject $object): array
    {
        $owned = self::owned($object);
        $identity = self::identity($object);
        $serial = [];

        foreach (self::defaults($object) as $column => $shape) {
            if ($shape === 'macro' && isset($owned[$column]) && ! isset($identity[$column])) {
                $serial[$column] = $owned[$column];
            }
        }

        return $serial;
    }

    /**
     * The columns that draw from a sequence they own, through a default this cannot read as `serial`.
     *
     * Sequence-driven and column-owned, but the default is `COALESCE(nextval('s'), 1)` or
     * `nextval('s') + 0` rather than the bare call — both constructible, both measured. Neither
     * answer is available: an identity column cannot express either expression, so recommending the
     * conversion would silently change what the column defaults to, and reporting nothing would
     * claim a check that did not happen.
     *
     * @return list<string>
     */
    public static function unreadable(SchemaObject $object): array
    {
        $owned = self::owned($object);
        $identity = self::identity($object);
        $unreadable = [];

        foreach (self::defaults($object) as $column => $shape) {
            if ($shape !== 'macro' && isset($owned[$column]) && ! isset($identity[$column])) {
                $unreadable[] = $column;
            }
        }

        return $unreadable;
    }

    /**
     * The sequence each column owns outright.
     *
     * @return array<string, string>
     */
    private static function owned(SchemaObject $object): array
    {
        return self::single($object, 'sequence_owned_columns');
    }

    /**
     * Each column's identity kind, for the columns that have one.
     *
     * @return array<string, string>
     */
    private static function identity(SchemaObject $object): array
    {
        return self::single($object, 'identity_columns');
    }

    /**
     * Each column's sequence-default shape — `macro` or `wrapped` — for the columns that have one.
     *
     * @return array<string, string>
     */
    private static function defaults(SchemaObject $object): array
    {
        return self::single($object, 'sequence_default_columns');
    }

    /**
     * One projection, read as column => its single value.
     *
     * The shared encoding carries a LIST per name because most projections describe key members.
     * These three carry exactly one value each, and an entry that somehow arrived empty is dropped
     * rather than read as an empty string — a blank shape would compare unequal to `macro` and
     * quietly land in the undetermined arm, which is the wrong place for a fact that is missing
     * rather than unreadable.
     *
     * @return array<string, string>
     */
    private static function single(SchemaObject $object, string $attribute): array
    {
        $values = [];

        foreach (ForeignKeyIndexCoverage::parse($object->getString($attribute) ?? '') as $column => $entries) {
            if ($entries !== []) {
                $values[$column] = $entries[0];
            }
        }

        return $values;
    }
}
