<?php

declare(strict_types=1);

namespace Pushery\SQLens\Generation\Renderers;

/**
 * The line that tells a reader this file is regenerated.
 *
 * Not politeness. These files look hand-written, live in version control, and will eventually be
 * edited by somebody who has no reason to suspect anything rewrites them — and their edit will be
 * thrown away on the next run, silently, in a diff that reads as noise. The notice is the only
 * thing standing between that person and an afternoon they will not get back.
 *
 * It names the command rather than the tool, because "regenerated" is useless without "by what".
 * It carries the catalog hash so a stale file can be recognized by eye as well as by `--check`,
 * and no timestamp — a timestamp would produce a diff on every run, which is how a generated file
 * teaches its readers to stop looking at diffs.
 */
final readonly class GeneratedNotice
{
    /** For a file this tool owns whole: the notice as the first prose in the document. */
    public static function forWholeFile(string $generatorVersion, string $snapshotHash): string
    {
        return '<!-- Generated by `php artisan sqlens:agent-rules` (v'.$generatorVersion.', catalog '
            .substr($snapshotHash, 0, 12).'). Edits are overwritten; change the SQLens config instead. -->';
    }
}
